name: Villa Serrana
favicon: null
layout_spectrum: 0.36319799721241
typography_spectrum: 0.34979720087721944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8583513533230871
  lightness: 0.9195955290924758
  saturation: 0.374992762459442
  rhythmicContrast: 0.22787825809791684
purpose: []
