name: Villa Serrana
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43559
title: Villa Serrana - Inmobelaria Mariana Nicolini
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d7dae3'
    - '#1c346a'
    - '#a1a0a6'
    - '#0b0a01'
  brandStrength: 0.8583513533230871
  lightness: 0.9195955290924758
  saturation: 0.374992762459442
  rhythmicContrast: 0.22787825809791684
purpose: []
